Repository youngeek-0410/sekigae, pull requests merged in 2022-01, with the labels that each got.

#4 feat: add ER diagram #3
  references/er.drawio
  references/er.png
Labels: task:backend, type:feature

#6 feat: update User API #5
  .gitignore
  fastapi/app/api/v1/auth.py
  fastapi/app/core/exceptions.py
  fastapi/app/core/settings.py
  fastapi/app/crud/base.py
  fastapi/app/crud/user.py
  fastapi/app/db/data.py
  fastapi/app/db/migrations/versions/20220101_132011_add_firebase_uid_to_user.py
  fastapi/app/db/seed.py
  fastapi/app/models/user.py
  fastapi/app/routers/v1/auth.py
  fastapi/app/schemas/auth.py
  fastapi/app/schemas/user.py
  fastapi/poetry.lock
  fastapi/pyproject.toml
Labels: task:backend, type:feature

#2 feat: first setup #1
  README.md
  package.json
Labels: task:infrastructure, type:feature

#11 Update docker code
  README.md
  docker-compose.yml
  env.sh
  fastapi/Dockerfile
  fastapi/alembic.ini
  fastapi/app/core/settings.py
  fastapi/entrypoint.sh
  fastapi/env.sh
  fastapi/fastapi.env.tmpl
  fastapi/scripts/server
  postgres/Dockerfile
Labels: task:infrastructure, type:enhancement

#12 fix: [Errno 2] No such file or directory: b'/bin/alembic'
  fastapi/Dockerfile
Labels: type:bug
